version: "3.7"

services:
  client:
    container_name: client
    image: simple-todo_client
    build:
      context: ./
      dockerfile: infra/prod/docker/client/Dockerfile

  nginx:
    container_name: nginx
    image: simple-todo_nginx
    restart: always
    build:
      context: ./
      dockerfile: infra/prod/docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - service

  service:
    container_name: service
    image: simple-todo_service
    build:
      context: ./
      dockerfile: infra/prod/docker/service/Dockerfile
