const todoActionTypes = {
    FETCH_ITEMS_START: 'FETCH_ITEMS_START',
    FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
    FETCH_ITEMS_FAILURE: 'FETCH_ITEMS_FAILURE',
    DELETE_ITEM_START: 'DELETE_ITEM_START',
    DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',
    DELETE_ITEM_FAILURE: 'DELETE_ITEM_FAILURE',
    ADD_ITEM_START: 'ADD_ITEM_START',
    ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
    ADD_ITEM_FAILURE: 'ADD_ITEM_FAILURE',
    UPDATE_ITEM_START: 'UPDATE_ITEM_START',
    UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
    UPDATE_ITEM_FAILURE: 'UPDATE_ITEM_FAILURE'
};

export default todoActionTypes;